version: "3.1"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=escola
